---
# based upon: https://github.com/BigWigsMods/packager/wiki/GitHub-Actions-workflow

# description of this workflow, can be anything you want
name: Package and release

# we need to let GitHub know _when_ we want to release, typically only when we create a new tag.
# this will target only tags, and not all pushes to the master branch.
on:
  push:
    tags:
      - '**'
    paths-ignore:
      - ".github/**"


# a workflow is built up as jobs, and within these jobs are steps
jobs:

  # "release" is a job, you can name it anything you want
  release:

    # we can run our steps on pretty much anything, but the "ubuntu-latest" image is a safe bet
    # ubuntu-24.04 a.k.a. ubuntu-latest has removed support for SVN, therefore the build breaks when fetching Ace3 externals
    runs-on: ubuntu-22.04

    # specify the environment variables used by the packager, matching the secrets from the project on GitHub
    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
      WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}

    # "steps" holds a list of all the steps needed to package and release our AddOn
    steps:

      # we first have to clone the AddOn project, this is a required step
      - name: Clone project
        uses: actions/checkout@main
        with:
          fetch-depth: 0

      # once cloned, we just run the GitHub Action for the packager project (builds 1 zip file with 3 TOC files)
      - name: Package and release
        uses: BigWigsMods/packager@v2
